2019-02-20 16:42:58,586 - D:/JKL_work/work/get_futuers_SP_data_/log_test.py[line:45] - ERROR: error
